version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: pedidos-postgres
    environment:
      POSTGRES_DB: pedidosdb
      POSTGRES_USER: pedidos_user
      POSTGRES_PASSWORD: pedidos_pass
    ports:
      - "5432:5432"
    volumes:
      - pedidos_postgres_data:/var/lib/postgresql/data
volumes:
  pedidos_postgres_data:
